language: node_js
node_js:
  - "14"
#  - "0.10" doesn't allow 'strict' keyword
#script: npm run test
before_script:
  - npm install -g gulp
script: gulp
notifications:
  email:
    - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true